### ISSUE TITLE
Make broker registration optional

### ISSUE THREAD

**Issue by juliapampus** [fkie/ids-configmanager-ui#13]
The user should be able to decide whether the connector should be registered or unregistered at the IDS metadata broker. Therfore, we may need a button at the broker overview.

**Comment by BastianWel** [comment]
API is needed to get the current registration status for every broker (registered/unregisterd) to display the corresponding button.
Issue added to [IDS-ConfigurationManager](https://github.com/FraunhoferISST/IDS-ConfigurationManager/)

**Comment by BastianWel** [comment]
Implemented in commit eb1d847
