### ISSUE TITLE
Broker registration for new and existing resources

### ISSUE THREAD

**Issue by juliapampus** [fkie/ids-configmanager-ui#14]
The resource process should have a button for registering or unregistering a resource to a chosen broker. Either after setting the backend source, or at the resource overview. Preferably both.

**Comment by BastianWel** [comment]
Added new tab "brokers" on "Add resource" page. 
Changing broker registration can be done with edit button.
"Edit resource" cannot be tested currently because of [Issue 19](https://github.com/FraunhoferISST/IDS-ConfigurationManager/issues/19)

**Comment by BastianWel** [comment]
Implemented in commit be56685
